name: "node_modules (npm)"
description: "Installing node_modules with npm. Wrapper around install-node-modules."

inputs:
  NPM_TOKEN:
    description: "Token for private GitHub Packages registry"
    required: true
  branch:
    description: "Git ref to checkout"
    required: true
  node-version-file:
    description: "File to read node version from. Leave empty to auto-detect."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: sfstudios/actions/install-node-modules@master
      with:
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        branch: ${{ inputs.branch }}
        package-manager: npm
        node-version-file: ${{ inputs.node-version-file }}
