name: "Install node_modules"
description: "Auto-detects package manager (npm, yarn, or bun) and installs dependencies with caching."

inputs:
  NPM_TOKEN:
    description: "Token for private GitHub Packages registry"
    required: true
  branch:
    description: "Git ref to checkout. Leave empty to skip checkout."
    required: false
    default: ""
  package-manager:
    description: "Force package manager: npm, yarn, bun, or auto (detect from lock file)"
    required: false
    default: "auto"
  node-version-file:
    description: "File to read node version from"
    required: false
    default: ".nvmrc"

runs:
  using: "composite"
  steps:
    # 1. Conditional checkout (backwards compat: old callers pass branch)
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ inputs.branch != '' }}
      with:
        ref: ${{ inputs.branch }}

    # 2. Auto-detect package manager from lock file
    - name: Detect package manager
      id: detect
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" != "auto" ]; then
          echo "manager=${{ inputs.package-manager }}" >> $GITHUB_OUTPUT
        elif [ -f "bun.lockb" ] || [ -f "bun.lock" ]; then
          echo "manager=bun" >> $GITHUB_OUTPUT
        elif [ -f "yarn.lock" ]; then
          echo "manager=yarn" >> $GITHUB_OUTPUT
        elif [ -f "package-lock.json" ]; then
          echo "manager=npm" >> $GITHUB_OUTPUT
        else
          echo "::error::No lock file found. Set package-manager input or add a lock file."
          exit 1
        fi

    # 3a. Setup Node with built-in caching and registry auth (npm or yarn)
    - name: Setup Node
      uses: actions/setup-node@v6
      if: ${{ steps.detect.outputs.manager != 'bun' }}
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ steps.detect.outputs.manager }}
        registry-url: "https://npm.pkg.github.com/"
        scope: "@sfstudios"

    # 3b. Setup Bun
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      if: ${{ steps.detect.outputs.manager == 'bun' }}

    # 3c. Setup Node alongside Bun (tools like tsc, eslint may need it)
    - name: Setup Node (for Bun projects)
      uses: actions/setup-node@v6
      if: ${{ steps.detect.outputs.manager == 'bun' }}
      with:
        node-version-file: ${{ inputs.node-version-file }}

    # 3d. Configure registry auth for bun
    #     Bun reads .npmrc natively. Repos already have the registry URL
    #     in .npmrc, so we just append the auth token.
    - name: Configure registry auth (bun)
      if: ${{ steps.detect.outputs.manager == 'bun' }}
      shell: bash
      run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.NPM_TOKEN }}" >> .npmrc

    # 4. Install dependencies
    - name: Install dependencies
      shell: bash
      run: |
        case "${{ steps.detect.outputs.manager }}" in
          npm)  npm ci ;;
          yarn) yarn install --frozen-lockfile ;;
          bun)  bun install --frozen-lockfile ;;
        esac
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
